kind: pipeline
type: docker
name: default
node:
  region: cn
steps:
  - name: docker-cn
    pull: if-not-exists
    image: plugins/docker
    settings:
      repo: ccr.ccs.tencentyun.com/xiaoqidun/palgs
      registry: ccr.ccs.tencentyun.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile